### PR TITLE
Fix returning draws/sampling diagnostics for warmup with no samples

### LINKED ISSUE #288: fit$sampler_diagnostics() not working correctly when iter_sampling = 0
For something like this:

```
fit1 = model$sample(data = data, parallel_chains = 4, save_warmup = 0, iter_warmup = 100, iter_sampling = 1, save_latent_dynamics = TRUE)
```

`sampler_diagnostics` output looks like:
```
# A draws_array: 1 iterations, 4 chains, and 6 variables
, , variable = accept_stat__

         chain
iteration 1    2    3    4
        1 1 0.43 0.98 0.99
...
```

For these commands (with and without `save_warmup = 1`):

```
fit2 = model$sample(data = data, parallel_chains = 4, save_warmup = 0, iter_warmup = 100, iter_sampling = 0, save_latent_dynamics = TRUE)

fit3 = model$sample(data = data, parallel_chains = 4, save_warmup = 1, iter_warmup = 100, iter_sampling = 0, save_latent_dynamics = TRUE)
```

We get:
```
> fit2$sampler_diagnostics()
NULL
```

and
```
# A draws_array: 2 iterations, 4 chains, and 6 variables
, , variable = accept_stat__

         chain
iteration    1    2    3    4
        1   NA   NA   NA   NA
        2 0.91 0.96 0.44 0.43
...
```

The first makes sense cause if there's no sampling and no save warmup, there's nothing to read.

The second doesn't really make sense. I'd expect a NULL unless I did `inc_warmup = TRUE`.

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Fixes #288 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Rok Češnovar, Univ. of Ljubljana

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

File: R/fit.R [hunk 1]
```diff
@@ -937,32 +937,36 @@ CmdStanMCMC <- R6::R6Class(
       private$metadata_ <- data_csv$metadata
 
       if (!is.null(data_csv$post_warmup_draws)) {
+        missing_variables <- !(posterior::variables(data_csv$post_warmup_draws) %in% posterior::variables(private$draws_))
```
Comment (rok-cesnovar) [inline R/fit.R:940]: This fixes an issue that is related to the main issue this PR is fixing. It was a bug all along but only surfaced with this.

```r
library(cmdstanr)
stan_program <- file.path(cmdstan_path(), "examples/bernoulli/bernoulli.stan")
model <- cmdstan_model(stan_program)

stan_data <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))
fit3 = model$sample(data = stan_data, parallel_chains = 4, save_warmup = 1, iter_warmup = 100, iter_sampling = 0, save_latent_dynamics = TRUE)

fit3$draws() #works fine
fit3$draws() #fails

fit3$sampler_diagnostics() #works fine
fit3$sampler_diagnostics() #fails
```

File: tests/testthat/test-fit-mcmc.R [hunk 2]
```diff
@@ -192,11 +198,15 @@ test_that("inc_warmup in draws() works", {
   y0 <- fit_mcmc_0$sampler_diagnostics(inc_warmup = FALSE)
   y1 <- fit_mcmc_1$sampler_diagnostics(inc_warmup = FALSE)
   y2 <- fit_mcmc_1$sampler_diagnostics(inc_warmup = TRUE)
+  y3 <- fit_mcmc_3$sampler_diagnostics(inc_warmup = TRUE)
+  y4 <- fit_mcmc_3$sampler_diagnostics(inc_warmup = FALSE)
```
Comment (rok-cesnovar) [inline tests/testthat/test-fit-mcmc.R:202]: Calling sampler_diagnostics() on the same fit would without https://github.com/stan-dev/cmdstanr/pull/293/files#r478645723

**Comment by rok-cesnovar** [comment]
Both this PR and #294 are ready for review.
