### PR TITLE
Windows fixes & installation helpers

### LINKED ISSUE #20: Check for (and install?) required tool chain
Should check what CmdStanPy does: https://github.com/stan-dev/cmdstanpy/blob/master/cmdstanpy/install_cxx_toolchain.py

### LINKED ISSUE #259: Prepend PATH with path to RTools on Windows
We have seen a few issues from users that turned out to be muliple g++ installed on the system. Typically some MinGw install or something along those lines.

What we could do is try to prepend the path to rtools on the front of PATH (like we do for TBB) which would then force the use of the right compiler.

We would check the usual paths to rtools and if found use it. If the user installed it in some non-typical location, then we would not prepend it.

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

- fixes #20 
- fixes #259 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Rok Češnovar, Uni. of Ljubljana

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

File: R/install.R [hunk 1]
```diff
@@ -396,3 +396,142 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+          )
+          stop(paste0(error_message, collapse = "\n"), call. = FALSE)
+        }
+      }
+    }
+  } else {
+    # On Unix systems we check for make and a suitable compiler
+    make_path <- dirname(Sys.which("make"))
+    if (!nzchar(make_path)) {
+      stop("The 'make' tool was not found. Please install 'make' and restart the R session.", call. = FALSE)
```
[the remark this answers is not in the document]
Comment (jgabry) [reply R/install.R:528]: I thought that `xcode-select --install` was enough but I think at one point @mitzimorris found that she had to install all of xcode. Mitzi am I remembering that correctly? So to be safe we can recommend installing all of xcode I guess. 

To detect if a user is on mac I think this should work:

```r
Sys.info()[["sysname"]] == "Darwin"
```

File: R/install.R [hunk 2]
```diff
@@ -396,3 +396,142 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+    }
+    gpp_path <- dirname(Sys.which("g++"))
+    clang_path <- dirname(Sys.which("clang++"))
+    if (!nzchar(gpp_path) && !!nzchar(clang_path)) {
+      stop("A C++ compiler was not found. Please install the 'clang++' of 'g++' compiler and restart the R session.", call. = FALSE)
```
[the remark this answers is not in the document]
Comment (jgabry) [reply R/install.R:533]: I think it's probably OK to just error on Mac. On Linux there's probably more of a chance of someone trying a different compiler so maybe a warning would be preferable. That said, I'd also be ok with an error and requiring the officially supported compiler.

File: R/install.R [hunk 3]
```diff
@@ -396,3 +396,142 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+  processx::run(
+    "pacman",
+    args = c("-Syu", "mingw-w64-x86_64-make","--noconfirm"),
+    wd = file.path(Sys.getenv("RTOOLS40_HOME"), "usr", "bin"),
+    error_on_status = TRUE
+  )
+  invisible(NULL)
+}
+
+install_cmdstan_toolchain <- function(check_only = FALSE) {
```
[the remark this answers is not in the document]
Comment (jgabry) [reply R/install.R:409]: Yeah running it with `check_only=TRUE` seems like a good idea.

File: R/install.R (hunk 1 above)
[the remark this answers is not in the document]
Comment (mitzimorris) [reply R/install.R:528]: regarding xcode - yes, I saw this during an upgrade to Catalina - under some circumstances this might be necessary - wish I understood which circumstance that is.   I tested a few different things - upgrade, upgrade + migration - on Bob's old 2011 MacBookPro - too many variables there.

**Comment by rok-cesnovar** [comment]
This now has all the functionalities it will have in the end. Its only missing tests for which I haven't completely thought out how to do. 

Current functionalities:
- `check_cmdstan_toolchain(fix = FALSE)` checks for make and g++/clang++
- `check_cmdstan_toolchain(fix = TRUE)` will fix what it can fix on Windows (install mingw32-make and fix PATH issues)
- `install_cmdstan()` calls `check_cmdstan_toolchain(fix = FALSE)`, but you can turn it off with check_toolchain = FALSE

The checks are: 

**Windows R4.0:** 
- is Rtools 4.0 installed?
- is RTools 4.0 installed in a valid path?
- are mingw32-make and g++ available?
- are mingw32-make and g++ that are picked up the ones in RTools 4.0?

**Windows R3.x:** 
- are mingw32-make and g++ available?
- if above is FALSE check a bunch of typical RTools 3.5 paths

**Unix:**
- check if make and g++ are available

File: R/install.R [hunk 4]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+            if (dir.exists(p)) {
+              rtools_path <- p
+            }
+          }
+        }
+        if (nzchar(rtools_path)) {
+          if (!fix) {
+            error_message <- c(
+              "",
+              "A RTools installation was found, but the PATH is not properly set.",
```
Comment (jgabry) [inline R/install.R:521]: For consistency with the same message above this should be 
```suggestion
              "RTools installation found but PATH was not properly set.",
```

File: R/install.R [hunk 5]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+              "Run 'cmdstanr::check_cmdstan_toolchain(check_only = FALSE)' to fix the issue."
```
Comment (jgabry) [inline R/install.R:522]:
```suggestion
              "Run check_cmdstan_toolchain(fix = TRUE) to fix the issue."
```

File: R/install.R [hunk 6]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+            )
+            stop(paste0(error_message, collapse = "\n"), call. = FALSE)
+          }
+          if (!quiet) message("Writing RTools path to ~/.Renviron ...")
```
Comment (jgabry) [inline R/install.R:526]: Nitpicking for style consistency: 

```suggestion
          if (!quiet) {
            message("Writing RTools path to ~/.Renviron ...")
          }
```

File: R/install.R [hunk 7]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+          if (nzchar(Sys.getenv("RTOOLS35_HOME"))) {
+            write(paste0('RTOOLS35_HOME=', rtools_path), file = "~/.Renviron", append = TRUE)
+          }
+          write('PATH="${RTOOLS35_HOME}\\bin;${RTOOLS35_HOME}\\mingw_64\\bin;${PATH}"', file = "~/.Renviron", append = TRUE)
+          stop("Restart R and run check_cmdstan_toolchain(check_only = TRUE) to confirm the installation was successful.", call. = FALSE)
```
Comment (jgabry) [inline R/install.R:531]:
```suggestion
          stop("Please restart R and run check_cmdstan_toolchain() to confirm the installation was successful.", call. = FALSE)
```

But since this same message is used many times maybe it's worth just making a helper function that returns this error message?

File: R/install.R [hunk 8]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+          error_message <- c(
+            "",
+            "A toolchain was not found. Please install RTools 3.5 and run",
+            "",
+            "write(\'RTOOLS35_HOME=rtools35/install/path/\', file = \"~/.Renviron\", append = TRUE)",
+            "replacing 'rtools35/install/path/' with the actual install path of RTools 3.5.",
+            "",
+            "Then restart R and run 'cmdstanr::check_cmdstan_toolchain(check_only = FALSE)'."
+          )
+          stop(paste0(error_message, collapse = "\n"), call. = FALSE)
```
Comment (jgabry) [inline R/install.R:542]: Oh, now I think I see why you're using the blank `""` in most of these error messages. If you prefer this way that's fine, but you can get the same output with fewer lines of code like this: 

```
stop(
  "A toolchain was not found. Please install RTools 3.5 and run",
  "\n\nwrite(\'RTOOLS35_HOME=rtools35/install/path/\', file = \"~/.Renviron\", append = TRUE)",
  "\nreplacing 'rtools35/install/path/' with the actual install path of RTools 3.5.",
  "\n\nThen restart R and run 'cmdstanr::check_cmdstan_toolchain(check_only = FALSE)'.", 
  call. = FALSE
)
```

In either case, `'cmdstanr::check_cmdstan_toolchain(check_only = FALSE)'` can be replaced with 
`check_cmdstan_toolchain(fix = TRUE)`

File: R/install.R [hunk 9]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+        }
+      }
+    }
+  } else {
+    # On Unix systems we check for make and a suitable compiler
+    make_path <- dirname(Sys.which("make"))
+    if (!nzchar(make_path)) {
+      if (os_is_macos()) {
+        stop("The 'make' tool was not found. Please install 'xcode' toolchains with 'xcode-select --install' or the app store and restart the R session.", call. = FALSE)
```
Comment (jgabry) [inline R/install.R:551]:
```suggestion
        stop("The 'make' tool was not found. Please install the command line tools for Mac with 'xcode-select --install' or install Xcode from the app store. Then restart R and run check_cmdstan_toolchain().", call. = FALSE)
```

File: R/install.R [hunk 10]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+      } else {
+        stop("The 'make' tool was not found. Please install 'make' and restart the R session.", call. = FALSE)
```
Comment (jgabry) [inline R/install.R:553]:
```suggestion
        stop("The 'make' tool was not found. Please install 'make', restart R, and then run check_cmdstan_toolchain().", call. = FALSE)
```

File: R/install.R [hunk 11]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+    clang_path <- dirname(Sys.which("clang++"))
+    if (!nzchar(gpp_path) && !nzchar(clang_path)) {
+      if (os_is_macos()) {
+        stop("A suitable C++ compiler was not found. Please install 'xcode' toolchains with 'xcode-select --install' or the app store and restart the R session.", call. = FALSE)
+      } else {
+        stop("A C++ compiler was not found. Please install the 'clang++' or 'g++' compiler and restart the R session.", call. = FALSE)
+      }
+    }
+  }
+  if (!quiet) message("The CmdStan toolchain is setup properly!")
```
Comment (jgabry) [inline R/install.R:567]: Nitpicking for code style consistency: 

```suggestion
  if (!quiet) {
    message("The CmdStan toolchain is setup properly!")
  }
```

File: R/install.R [hunk 12]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+      } else {
+        stop("The 'make' tool was not found. Please install 'make' and restart the R session.", call. = FALSE)
+      }
+      
+    }
+    gpp_path <- dirname(Sys.which("g++"))
+    clang_path <- dirname(Sys.which("clang++"))
+    if (!nzchar(gpp_path) && !nzchar(clang_path)) {
+      if (os_is_macos()) {
+        stop("A suitable C++ compiler was not found. Please install 'xcode' toolchains with 'xcode-select --install' or the app store and restart the R session.", call. = FALSE)
```
Comment (jgabry) [inline R/install.R:561]:
```suggestion
        stop("A suitable C++ compiler was not found. Please install the command line tools for Mac with 'xcode-select --install' or install Xcode from the app store. Then restart R and run check_cmdstan_toolchain().", call. = FALSE)
```

File: R/install.R [hunk 13]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+      } else {
+        stop("A C++ compiler was not found. Please install the 'clang++' or 'g++' compiler and restart the R session.", call. = FALSE)
```
Comment (jgabry) [inline R/install.R:563]:
```suggestion
        stop("A C++ compiler was not found. Please install the 'clang++' or 'g++' compiler, restart R, and run check_cmdstan_toolchain().", call. = FALSE)
```

File: R/install.R [hunk 14]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+#'
+check_cmdstan_toolchain <- function(fix = FALSE, quiet = FALSE) {
+  if(os_is_windows()) {
+    if (R.version$major >= "4") {
+      rtools_path <- Sys.getenv("RTOOLS40_HOME")
+      # If RTOOLS40_HOME is not set (the env. variable gets set on install)
+      # we assume that RTools 40 is not installed.
+      if (!nzchar(rtools_path)) {
+        error_message <- c(
+          "",
```
[the remark this answers is not in the document]
Comment (rok-cesnovar) [reply R/install.R:439]: Yeah, to make newlines. Fixed by using "\n" directly.

File: R/install.R [hunk 15]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+      if (regexpr("\\(|)| ", rtools_path) > 0) {
+        error_message <- c(
+          "",
+          "RTools 4.0 is installed in a path with spaces or brackets, which is not supported.",
+          "Reinstall RTools 4.0 to a valid path, restart R and run 'cmdstanr::check_cmdstan_toolchain()'"
+        )
+        stop(paste0(error_message, collapse = "\n"), call. = FALSE)
+      }
+      if (fix) {
+        install_mingw32_make()
```
[the remark this answers is not in the document]
Comment (rok-cesnovar) [reply R/install.R:456]: It wont reinstall mingw32-make if its already installed and no updated versions are available, which I think is fine. Its also quick in that case.

Moved it now to only run if mingw32-make/g++ are not found or the wrong mingw32-make/g++ are picked up.

File: R/install.R [hunk 16]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+            file.path("c:/", "Rtools"),
+            file.path("c:/", "Rtools35"),
+            file.path("c:/", "RTools"),
+            file.path("c:/", "RTools35"),
+            file.path("c:/", "rtools"),
+            file.path("c:/", "rtools35")
+          )
+          for (p in typical_paths) {
+            if (dir.exists(p)) {
+              rtools_path <- p
```
[the remark this answers is not in the document]
Comment (rok-cesnovar) [reply R/install.R:515]: Good question. Moved to erroring if multiple found.

File: R/install.R (hunk 8 above)
Comment (rok-cesnovar) [reply R/install.R:546]: Thanks, replaced with your suggestion.

File: R/install.R [hunk 17]
```diff
@@ -396,3 +398,172 @@ build_status_ok <- function(process_log, quiet = FALSE) {
...
+    args = c("-Syu", "mingw-w64-x86_64-make","--noconfirm"),
+    wd = file.path(Sys.getenv("RTOOLS40_HOME"), "usr", "bin"),
+    error_on_status = TRUE
+  )
+  invisible(NULL)
+}
+
+check_compiler_version <- function(compiler = c("g++", "clang++")) {
+
+}
```
[the remark this answers is not in the document]
Comment (rok-cesnovar) [reply R/install.R:416]: At first I meant to define it but I later figured it will be challenging, because we cant really know whether the user uses g++ or clang before building cmdstan. We should add a compiler check command to cmdstan makefiles. 
We can use that then. 

Too old compiler is generally not a huge support problem. Nowadays its mostly seen when users move to a cluster, where some popular distributions still come with g++ 4.8.x. But users mostly run cmdstan directly on a cluster.

**Comment by rok-cesnovar** [comment]
> Then `check_cmdstan_toolchain()` can call those functions and it would be much easier to tell what `check_cmdstan_toolchain()` is doing. Does that make sense? If so, what do you think?

Completely agree. Split the function now.

Also addressed all your other comments and applied the suggested fixes. Thanks for those! They were really helpful.

This is now ready in terms of functionalities, though I wont to go over it again (I have AWS instances with various setups to test this). I would also like to add a few unit tests where it's possible. It's not possible for all cases. Will add those Monday/Tuesday and will then tag you for another review.

**Comment by jgabry** [comment]
Ok great, sounds good. Thanks!

**Comment by rok-cesnovar** [comment]
Note to self: check that we have write access to the Rtools folder before trying to install mingw32-make.

**Comment by jgabry** [comment]
@rok-cesnovar I see this is passing all the checks now. Is it ready for another review or are you still working on it? No rush, just checking.

**Comment by rok-cesnovar** [comment]
Still missing tests. Sorry, still haven't gotten back to this.

**Comment by jgabry** [comment]
> Sorry, still haven't gotten back to this.

No worries!

**Comment by jgabry** [comment]
And definitely no rush if you’ve got a lot going on. This can wait!

**Comment by rok-cesnovar** [comment]
This is now ready for merging. I added some tests.

File: R/install.R [hunk 18]
```diff
@@ -48,6 +52,9 @@
 #' @param cpp_options A list specifying any makefile flags/variables to be
 #'   written to the `make/local` file. For example, `list("CXX" = "clang++")`
 #'   will force the use of clang for compilation.
+#' @param check_toolchain A list specifying any makefile flags/variables to be
```
Comment (jgabry) [inline R/install.R:55]: Just noticed that the doc is wrong here. I think it's just a copy/paste error. check_toolchain should be T/F right?

File: R/install.R [hunk 19]
```diff
@@ -30,8 +30,12 @@
...
 #'   session by `options(mc.cores=value)`. If the `"mc.cores"` option has not
 #'   been set then the default is `2`.
-#' @param quiet Should the verbose output from the system processes be
-#'   suppressed when building the CmdStan binaries? The default is `FALSE`.
+#' @param quiet For `install_cmdstan()`, should the verbose output from the
+#'   system processes be suppressed when building the CmdStan binaries?
+#'   The default is `FALSE`.
+#'   For `check_cmdstan_toolchain()`, should the function supress 
+#'   printing informational messages? The default is `FALSE`.
+#'   If `TRUE` `check_cmdstan_toolchain()` only output errors.
```
Comment (jgabry) [inline R/install.R:38]:
```suggestion
#'   If `TRUE` `check_cmdstan_toolchain()` only outputs errors.
```

**Review by jgabry — COMMENTED** [review]
Awesome, thanks for adding the tests.  Found a few tiny doc things, but then merging is fine by me. This will be great to have.

File: R/install.R (hunk 18 above)
Comment (rok-cesnovar) [reply R/install.R]: Indeed. A copy paste error. Fixed now. Thanks!

**Comment by rok-cesnovar** [comment]
Thanks! Will merge once tests pass.
