### PR TITLE
use read.csv if vroom fails

### LINKED ISSUE #249: Fall back to read.csv in case of a vroom error
Suggested by @maedoc

The idea in pseudocde is: 
```
try {
//read with vroom
} catch {
warning("There was an issue with reading the CSV file with vroom. Using the utils::read_csv")
// read entire file with read_csv
}
```

@jgabry something like this would do? Any suggestions on the message?

### PR DESCRIPTION
**Pull request by jgabry**
Fixes #249

#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Uses `utils::read_csv()` if `vroom::vroom()` errors. Throws a warning asking users to report. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

File: R/read_csv.R [hunk 1]
```diff
@@ -204,41 +206,44 @@ read_cmdstan_csv <- function(files,
       all_draws <- 1
     }
 
+    vroom_args <- list(
```
Comment (jgabry) [inline R/read_csv.R:209]: In order to not have to do try() multiple times, make list of vroom arguments so we only need one call to vroom() in the code. previously we had separate calls depending on generated quantities or not.

File: R/read_csv.R [hunk 2]
```diff
@@ -204,41 +206,44 @@ read_cmdstan_csv <- function(files,
...
-          n_max = all_draws * 2
+      vroom_args$col_types <- c("lp__" = "d")
+      vroom_args$n_max <- all_draws * 2
+    }
+
+    draws <- try(silent = TRUE, expr = {
+      suppressWarnings(do.call(vroom::vroom, vroom_args))
+    })
+    if (inherits(draws, "try-error")) {
+      if (vroom_warnings == 0) { # only warn the first time instead of for every csv file
```
Comment (jgabry) [inline R/read_csv.R:232]: Checking that we haven't yet thrown the warning let's us warn once instead of repeating the warning every csv file

File: R/read_csv.R [hunk 3]
```diff
@@ -204,41 +206,44 @@ read_cmdstan_csv <- function(files,
...
-          progress = FALSE,
-          skip = metadata$lines_to_skip,
-          n_max = all_draws * 2
+      vroom_args$col_types <- c("lp__" = "d")
+      vroom_args$n_max <- all_draws * 2
+    }
+
+    draws <- try(silent = TRUE, expr = {
+      suppressWarnings(do.call(vroom::vroom, vroom_args))
+    })
```
Comment (jgabry) [inline R/read_csv.R:230]: Not sure how to add a unit test for this, so to verify the behavior you can temporarily change this to 

```r
draws <- try(silent = TRUE, expr = stop())
```

which will force it to error and you can verify that it successfully uses read.csv() instead and throws the warning.

File: R/read_csv.R [hunk 4]
```diff
@@ -121,6 +121,8 @@ read_cmdstan_csv <- function(files,
   col_types <- NULL
   col_select <- NULL
   not_matching <- c()
+  vroom_warnings <- 0
```
Comment (jgabry) [inline R/read_csv.R:124]: Keep track of whether we've thrown a warning so that we can avoid throwing it for every csv file. Once per call to read_cmdstan_csv() seems like enough.

File: R/read_csv.R (hunk 3 above)
Comment (rok-cesnovar) [reply R/read_csv.R:230]: Not sure how to make it error either. I think its fine without a test for now. If we think of something we can add it later.

**Comment by jgabry** [comment]
I think I should have bumped the version number with this so we can tell if the user has this version. Are you ok if I do that now on master?

**Comment by rok-cesnovar** [comment]
Yeah sure!
