### PR TITLE
fix loading if no previous cmdstan installation

### LINKED ISSUE #274: Can't devtools::install_github("stan-dev/cmdstanr")
I'm trying to install cmdstanr from GitHub via `devtools::install_github("stan-dev/cmdstanr")` 

**Expected behavior**

Successful package install followed by the need to call `cmdstanr::install_cmdstan()`, which installs CmdStan and sets the path.

**Error**

Installation fails with the following:

```
✔  checking for file ‘/tmp/RtmpRH3cgr/remotesb1b5b912816/stan-dev-cmdstanr-edf9bad/DESCRIPTION’ ...
─  preparing ‘cmdstanr’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘cmdstanr_0.1.1.tar.gz’
   
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘cmdstanr’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘cmdstanr’:
 .onAttach failed in attachNamespace() for 'cmdstanr', details:
  call: NULL
  error: CmdStan path has not been set yet. See ?set_cmdstan_path.
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/cmdstanr’
Error: Failed to install 'cmdstanr' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpRH3cgr/fileb1b12559732/cmdstanr_0.1.1.tar.gz’ had non-zero exit status
```

**To Reproduce**
On a fresh machine image without the package or CmdStan installed / path set run `devtools::install_github(...)`

**Operating system**
Amazon Linux 2 AMI

**CmdStanR version number**
GitHub master

**Additional context**

I can still install via `install.packages("cmdstanr", repos = ...)`

### PR DESCRIPTION
**Pull request by jgabry**
closes #274

#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

I think this fixes #274. We forgot about the case when there is no pre-existing CmdStan installation! 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

File: R/zzz.R [hunk 1]
```diff
@@ -24,8 +24,10 @@ startup_messages <- function() {
   ))
   if (!skip_version_check) {
     latest_version <- try(suppressWarnings(latest_released_version()), silent = TRUE)
+    current_version <- try(cmdstan_version(), silent = TRUE)
```
Comment (jgabry) [inline R/zzz.R:27]: I think the problem was that the code assumed it could always check the current version number

Comment (rok-cesnovar) [reply R/zzz.R:27]: Yep!

devtools::install_github("stan-dev/cmdstanr@fix-274")

works if I clean out `~/.cmdstanr/`

Comment (jgabry) [reply R/zzz.R:27]: Great, works for me too

Comment (jgabry) [reply R/zzz.R:27]: I'll merge this as soon as the checks pass
