### PR TITLE
Warning but no error if `compile_standalone` but no functions found

### LINKED ISSUE #947: Standalone compilation poorly handles absent/empty functions block
Compilation with the `standalone` option fails poorly when there is in fact no `functions` block or when it's empty.
This is not entirely unreasonable, but arguably it should fail more gracefully, not with an obscure Rcpp error?
Ideally it would simply ignore the lack of functions and perform a regular compilation, perhaps with a warning that no functions were present?

```
library(cmdstanr)

stan_model_no_funs <- 
  "
  data {
    int<lower=0> N;
    array[N] int<lower=0,upper=1> y;
  }
  parameters {
    real<lower=0,upper=1> theta;
  }
  model {
    theta ~ beta(1,1);  // uniform prior on interval 0,1
    y ~ bernoulli(theta);
  }
  "

stan_empty_funs <- 
  "
  functions {
  }
  "

readr::write_lines(
  file = 'model_no_funs.stan'
  , x = stan_model_no_funs
)
cat(readr::read_file('model_no_funs.stan'))

readr::write_lines(
  file = 'model_empty_funs.stan'
  , x = paste(stan_empty_funs, stan_model_no_funs)
)
cat(readr::read_file('model_empty_funs.stan'))


# compiling works in the absence of a functions block or when it's empty

cmdstanr::cmdstan_model(compile = TRUE, compile_standalone = FALSE, 
                        stan_file = 'model_no_funs.stan')
cmdstanr::cmdstan_model(compile = TRUE, compile_standalone = FALSE, 
                        stan_file = 'model_empty_funs.stan')

# Compiling fails badly with standalone option.

try(cmdstanr::cmdstan_model(compile = TRUE, compile_standalone = TRUE, 
                        force_recompile = TRUE,
                        stan_file = 'model_no_funs.stan'))

try(cmdstanr::cmdstan_model(compile = TRUE, compile_standalone = TRUE,
                        force_recompile = TRUE,
                        stan_file = 'model_empty_funs.stan'))

```

macOS 14.4.1
RStudio 2023.06.1+524
cmdstanr version 0.7.1
CmdStan version: 2.34.1

### PR DESCRIPTION
**Pull request by jgabry**
closes #947

#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Continue with compilation if `compile_stanalone=TRUE` but no functions are found. Changes mysterious Rcpp error to an informative warning. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting
(this will be you or your assignee, such as a university or company):
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -979,6 +979,11 @@ expose_stan_functions <- function(function_env, global = FALSE, verbose = FALSE)
     stop("Exporting standalone functions with external C++ is not available before CmdStan 2.32",
          call. = FALSE)
   }
+  if (!is.null(function_env$hpp_code) &&
+      !any(grepl("[[stan::function]]", function_env$hpp_code, fixed = TRUE))) {
```
Comment (jgabry) [inline R/utils.R:983]: @andrjohns Is this an ok way to check whether there are any user defined functions?

Comment (andrjohns) [reply R/utils.R:983]: Yep, looks right to me

**Review by andrjohns — APPROVED** [review]
Thanks! I've also updated the `model-expose-functions` test to be entirely skipped on WSL - so that we don't have to keep adding skips to the individual tests (which was this failed before)
