### PR TITLE
Fix travis recompilation test

### LINKED ISSUE #86: test for change in compiler flags fails only on travis
_Originally posted by @jgabry in https://github.com/stan-dev/cmdstanr/pull/85#issuecomment-554787380_: 

the error is `"cannot open the connection"`, so it doesn't seem to be coming from recompilation but rather from trying to write to `make_local_path`: 

```r
 ── 1. Error: compile() method forces recompilation if changes in flags (@test-mo
  cannot open the connection
  Backtrace:
   1. testthat::expect_message(mod$compile(threads = TRUE), "change in the compiler flags was found")
   6. mod$compile(threads = TRUE)
   7. cmdstanr:::set_make_local(...)
   8. base::writeLines(make_local_content, make_local_path)
   9. base::file(con, "w")
```

The test is this one: https://github.com/stan-dev/cmdstanr/blob/342c22d920026fdbc60c930756928517ce566f9d/tests/testthat/test-model-compile.R#L36-L50

### PR DESCRIPTION
**Pull request by jgabry**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Fixes #86 

The problem turned out to be that `make/local` didn't exist and we didn't have sufficient permissions in that travis directory in order to create it via `writeLines()` in `set_make_local()`. So I ended up creating `make/local` and changing the permissions in `before_install` in `.travis.yml`: 

```
before_install:
  - sudo bash inst/make_cmdstan.sh -j2 -o
  - sudo touch $HOME/.cmdstanr/cmdstan/make/local
  - sudo chown -R $USER:$USER $HOME/.cmdstanr/cmdstan/make/local
```

I'm not sure if this is the best way of resolving this but it seems to work. @rok-cesnovar If you have a better idea I'm happy to go with a different solution. 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
**Columbia University**

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -308,6 +308,7 @@ set_make_local <- function(threads = FALSE,
   user_flags <- c()
   old_make_local_cmdstanr <- c()
   if (file.exists(make_local_path)) {
+    checkmate::assert_file_exists(make_local_path, access = 'rw')
```
Comment (jgabry) [inline R/utils.R]: I added this here and below just as an extra safeguard to throw an error if we don't have read and write permissions for `make/local`

Comment (rok-cesnovar) [reply R/utils.R]: Great!
