### PR TITLE
Fix trailing slash on directories windows bug

### LINKED ISSUE #281: Output directory errors with trailing slash on Windows
Someone told me that they were having troubles specifying the `output_dir` argument with a trailing slash. I checked in Linux and it works so maybe this is a Windows thing?

Close if it's not possible to reproduce.

Here's a model:
```
parameters {
  real a;
}

model {
  a ~ normal(0, 1);
}
```

Here's R to get an error:
```
library(cmdstanr)
model = cmdstan_model("test.stan")
dir.create("whatever")
fit = model$sample(output_dir = "./whatever/")
```

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and agree to license (see below)

#### Summary

Fixes #281 

Originally planned to do this as part of #289 but that might take a bit longer to polish so we can fix this here

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting 
(this will be you or your assignee, such as a university or company): 
Rok Češnovar, Univ. of Ljubljana

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the following licenses:

- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

File: R/fit.R [hunk 1]
```diff
@@ -937,32 +937,36 @@ CmdStanMCMC <- R6::R6Class(
       private$metadata_ <- data_csv$metadata
 
       if (!is.null(data_csv$post_warmup_draws)) {
+        missing_variables <- !(posterior::variables(data_csv$post_warmup_draws) %in% posterior::variables(private$draws_))
```
Comment (jgabry) [inline R/fit.R:940]: Is this stuff related to some other issue besides the trailing slash problem?

Comment (rok-cesnovar) [reply R/fit.R:940]: Ah sorry, that should be a part of https://github.com/stan-dev/cmdstanr/pull/293
I had both on the same branch then split them up.
